### ISSUE TITLE
Missing .venv

### ISSUE THREAD

**Issue by david-waterworth** [vmthanh/ml-demo-api-with-celery#1]
Nice article - just a note the .venv file is missing from `boot/docker/compose/trip_duration_prediciton/`

Also the image you used in the Medium article (`nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04`) doesn't appear to be available anymore - the oldest officially available image appears to be cuda:11-1-1 (https://hub.docker.com/r/nvidia/cuda/tags?page=1&ordering=-last_updated). I did find an unofficial version (ogvalt/cuda:9.0-cudnn7.0-devel-ubuntu16.04) which I used for now as I didn't want to spend time working out which official version worked. 

Finally I had to change `docker-compose` (original 3rd party python script) to `docker compose` (native extension)

**Comment by david-waterworth** [comment]
PS I found the official image at `nvcr.io/nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04`

**Comment by vmthanh** [comment]
Thanks for pointing out. I updated the missing .env
